#define XDFTFILEVERSION 	2, 2, 1, 1
#define XDFTPRODUCTVERSION 	2, 2, 1, 1
#define XDFTFILEVERSIONSTR "2.2.1.1"
#define XDFTPRODUCTVERSIONSTR "2.2.1.1"
#define XDFTLEGALCOPYRIGHTSTR "Copyright (c) 2020 by Wayne E. Wright, W5XD"
