#define XDFTFILEVERSION 	2, 2, 1, 6
#define XDFTPRODUCTVERSION 	2, 2, 1, 6
#define XDFTFILEVERSIONSTR "2.2.1.6"
#define XDFTPRODUCTVERSIONSTR "2.2.1.6"
#define XDFTLEGALCOPYRIGHTSTR "Copyright (c) 2020 by Wayne E. Wright, W5XD"
